[project]
name = "terraforming-mars"
version = "0.1.0"
description = "Simulation and ML recommendation project for Terraforming Mars"
requires-python = ">=3.9"

dependencies = [
    "numpy",
    "pandas",
    "xgboost",
    "scikit-learn"
]